Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: sp
    SupplierDeployMetadata:
      RoleName: ${RoleName}
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: 'templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Parameters:
                EcsInstanceType: ecs.c6.large
              Type: Noraml
              OrderList:
                - EcsInstanceType
            - Name: 基础版
              Parameters:
                EcsInstanceType: ecs.c6.xlarge
              Type: Noraml
              OrderList:
                - EcsInstanceType
            - Name: 高配版
              Parameters:
                EcsInstanceType: ecs.c6.2xlarge
              Type: Noraml
              OrderList:
                - EcsInstanceType
          HiddenParameterKeys:
            - EcsIntanceType
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: ${VpcId}
                    ZoneId: ${ZoneId}
                    VSwitchId: ${VSwitchId}
      FileArtifactRelation:
        '{{ computenest::file::springboot }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'templates/parameters.yaml'
        AllowedRegions:
          - cn-hangzhou
        PredefinedParameters:
        - Name: 低配版
          Parameters: {}
          Description: 该套餐采用了2vCPU 4GB内存的ECS实例（ecs.c6.large），系统盘采用200G的cloud_essd，可以满足基本的业务需求。
          Type: Noraml
          OrderList:
            - EcsInstanceType
        - Name: 基础版
          Parameters: {}
          Description: 该套餐采用了4vCPU 8GB内存的ECS实例（ecs.c6.xlarge），系统盘采用200G的cloud_essd，该配置可以满足大部分的业务需求。
          Type: Noraml
          OrderList:
            - EcsInstanceType
        - Name: 高配版
          Parameters: {}
          Description: 该套餐采用了8vCPU 16GB内存的ECS实例（ecs.c6.2xlarge），系统盘采用200G的cloud_essd，该配置使用了更高规格ECS，进一步提升了整体稳定性和性能。
          Type: Noraml
          OrderList:
            - EcsInstanceType
    NetworkMetadata:
      EnablePrivateVpcConnection: false
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: springboot demo
    Image: 'icons/service_logo.png'
    Name: SpringBoot单机托管版
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: SpringBootPackage
    Description: 这是一个使用SpringBoot的测试包
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'artifacts/package.tgz'